#name: Format Java code as per Google java format program
#
#on: [ push, pull_request ]
#
#jobs:
#
#  formatting:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4 # v2 minimum required
#
#      - uses: axel-op/googlejavaformat-action@4
#        with:
#          args: "--set-exit-if-changed"
