name: reusable-workflow-template

on:
  workflow_call:
    inputs:
      tests-to-exclude:
        required: false
        type: string
        default: "flaky, failing"
      tests-to-include:
        required: true
        type: string
        default:
      test-environment:
        required: false
        type: string
        default: "DEVELOP"
      run-name:
        required: false
        type: string
        default: "CI triggered"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Build with Maven
        run: >
          mvn -DexcludedGroups="${{ inputs.tests-to-exclude}}" 
          -Dgroups="${{ inputs.tests-to-include}}" 
          -DTEST_ENV="${{ inputs.test-environment}}" 
          -DTRIGGERED_BY="${{ github.event_name }}" 
          -DRUN_NAME="${{ inputs.run-name}}" 
          -B package --file pom.xml